
MethodLength:
  Max: 200

LineLength:
  Max: 160

AbcSize:
  Max: 220

FileName:
  Enabled: false

Style/SymbolArray:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FlipFlop:
  Enabled: false

# testing
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'sensu-plugins-openbsd.gemspec'
