language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.1
- 2.2
- 2.3.0
- 2.4.1
- 2.5.1
notifications:
  email:
    recipients:
    - support@sigterm.no
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-openbsd.gemspec
- gem install sensu-plugins-openbsd-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: 
  gem: sensu-plugins-openbsd
  on:
    tags: true
    repo: sensu-plugins/sensu-plugins-openbsd
    all_branches: true
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    rvm: 2.5.1
